// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = WhatWeHaveSlice;

/**
 * Content for about documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *about*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Description field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *about*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

export type AllDocumentTypes = AboutDocument;

/**
 * Primary content in *WhatWeHave → Primary*
 */
export interface WhatWeHaveSliceDefaultPrimary {
  /**
   * Title field in *WhatWeHave → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_have.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *WhatWeHave → Items*
 */
export interface WhatWeHaveSliceDefaultItem {
  /**
   * Car name field in *WhatWeHave → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_have.items[].car_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  car_name: prismic.KeyTextField;

  /**
   * Color field in *WhatWeHave → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_have.items[].color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Default variation for WhatWeHave Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatWeHaveSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatWeHaveSliceDefaultPrimary>,
  Simplify<WhatWeHaveSliceDefaultItem>
>;

/**
 * Slice variation for *WhatWeHave*
 */
type WhatWeHaveSliceVariation = WhatWeHaveSliceDefault;

/**
 * WhatWeHave Shared Slice
 *
 * - **API ID**: `what_we_have`
 * - **Description**: WhatWeHave
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatWeHaveSlice = prismic.SharedSlice<
  "what_we_have",
  WhatWeHaveSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AllDocumentTypes,
      WhatWeHaveSlice,
      WhatWeHaveSliceDefaultPrimary,
      WhatWeHaveSliceDefaultItem,
      WhatWeHaveSliceVariation,
      WhatWeHaveSliceDefault,
    };
  }
}
